### ISSUE TITLE
Missing `pattern` label

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-labels#12]
We add this label for any new pattern proposal but we don't actually have the label yet!
https://github.com/Financial-Times/origami/blob/master/.github/ISSUE_TEMPLATE/pattern-proposal.md
what color should this label be?

**Comment by notlee** [comment]
I don't actually feel I'd use that label. I would be in favor of removing it

**Comment by chee** [comment]
it's automatically added when somebody creates a `pattern` type issue, which is one of the two issue types that were split from the original issue template in the origami-proposals repo.

**Comment by chee** [comment]
i think we should have it and that it should be claret-30
