### ISSUE TITLE
Proposal: "next up" label

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-labels#15]
We have a "current" label for issues we've planned to work on over our 6
week planning cycle.
<img width="342" alt="Screenshot 2020-04-03 at 14 42 37" src="https://user-images.githubusercontent.com/10405691/78367059-63ae7a80-75b9-11ea-9d14-8713954f883d.png">

For larger issues we should discuss in our next planning session it would
be useful to have a "next up", or similar label, of the same colour.

Thoughts?

**Comment by chee** [comment]
love it!

i'd like to make two adjustments:

1. having a single word makes it nicer to type in the filter box (don't need quotes) so `coming` or `forthcoming` or `next` or `pending` or something would be preferable
2. the colour of current is a mandarin paper mix, right? i'd quite like it if this label was also a mix of the same colours but a different mix!

**Comment by notlee** [comment]
Sounds good to me! Shall we go with `pending`? The others sound like it's something we've committed to when actually we're just going to take a closer look

**Comment by notlee** [comment]
okay so:

**label:** `pending` 
**description:** `Used to mark an issue to discuss in Origami's next six-week planning cycle` 
**color:** mandarin-white-80

The `current` label is a darker  mandarin at mandarin-white-60, which I prefer as current issues should stand out as our main focus.

<img width="161" alt="Screenshot 2020-04-17 at 15 01 46" src="https://user-images.githubusercontent.com/10405691/79577391-9168e880-80bc-11ea-8e1b-d49645b55191.png">

**Comment by JakeChampion** [comment]
> okay so how about this @Financial-Times/origami-core
> 
> **label:** `pending`
> **description:** `Used to mark an issue to discuss in Origami's next six-week planning session`
> **color:** `mandarin-white-80`

Yes, let's do this 👍

**Comment by chee** [comment]
love it:)

**Comment by notlee** [comment]
I mixed the colours the other way around, so it's actually mandarin-white-40 to get lighter

**Comment by notlee** [comment]
https://github.com/Financial-Times/origami-labels/pull/18
