### ISSUE TITLE
proposal: make the release:patch colour something happier

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-labels#26]
i understand we made the `release:*` colours map to the `breaking` `feature` and `bug` colours because they are sort of the same thing (though a patch might also be a documentation change). but i think we should make the release:patch colour be a HAPPY colour, because we fixed the bug! in fact, i think all the release colours should be happy

the current release:patch colour makes me feel in trouble every time i do a patch! i'm improving documentation!!!

**Comment by notlee** [comment]
I'm onboard with minor and patch being a more happy colour :) but personally I appreciate the major release label being red to match the breaking label, it's a good prompt to be more careful with breaking changes

**Comment by JakeChampion** [comment]
Now we need to come up with some colours to use for this 😄
